//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logıstıc.UILayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMap
    {
        public int MapID { get; set; }
        public string MapLocationInfo { get; set; }
    }
}
